/**
 * GENERATED by scripts/discover-job-trends.ts on 2026-06-17. Do not hand-edit;
 * re-run the discovery script (it re-measures live jobs-scoped data) instead.
 *
 * Two galleries for the "Who is hiring?" search page:
 *   - CATEGORY_CARDS: themed "Top N <category>" lists (>=4 terms each), each a
 *     relative stacked-bar mini chart over live jobs data.
 *   - COMPARISONS: head-to-head stories (2-4 terms, incl. |-OR-group bars) plus
 *     any small (<=3-term) category demoted here per the "Top N is a real list"
 *     rule.
 *
 * Selection metric (over live scope=jobs aggregates): popularity (all-time
 * mention total) x shock factor (peak prominence + tower ratio + lead-change
 * crossover). Every term was probed live: none is dead (>= 150 mentions)
 * and no comparison is a flat line (some term's relative share swings >= 0.12
 * over time, or the leader changes hands at least once).
 *
 * Tokenization collisions deliberately excluded (the index tokenizer aliases
 * these onto noisier tokens):
 *   - go (English verb floods the token; use golang)
 *   - c, c++, c# (single chars collapse to token 'c' -> identical inflated count)
 *   - embeddings (same stem as 'embedded' -> identical count; keep one)
 *   - .net / asp.net (dot-split noise; low, unreliable counts)
 *
 * `|` inside a term string is an OR-group: parts are aggregated separately and
 * summed bucket-for-bucket into one series/bar.
 */

export type GalleryCard = {
  /** display title (e.g. "Top 8 languages" or a head-to-head label). */
  title: string;
  /** each string is one series; `|` inside = OR-group (summed into one bar). */
  terms: string[];
  /** one-line editorial story shown under the card. */
  story: string;
};

/** Themed "Top N <category>" cards (>=4 terms each), ranked by interestingness. */
export const CATEGORY_CARDS: GalleryCard[] = [
  {
    title: "Top 8 locations",
    terms: ["remote", "san francisco", "new york", "london", "seattle", "berlin", "austin", "amsterdam"],
    story: "Where the jobs are - and how remote stacks up against the hubs.",
  },
  {
    title: "Top 8 languages",
    terms: ["python", "javascript", "ruby", "typescript", "java", "php", "scala", "golang"],
    story: "The most-requested programming languages across every hiring thread.",
  },
  {
    title: "Top 8 frontend frameworks",
    terms: ["react", "angular", "vue", "backbone", "jquery", "ember", "nextjs", "svelte"],
    story: "Frontend frameworks as they rise and fade in job reqs.",
  },
  {
    title: "Top 8 backend frameworks",
    terms: ["rails", "django", "flask", "express", "spring", "phoenix", "laravel", "symfony"],
    story: "Backend and web frameworks companies staff up for.",
  },
  {
    title: "Top 6 mobile",
    terms: ["ios", "android", "react native", "swift", "kotlin", "flutter"],
    story: "Mobile platform and cross-platform demand.",
  },
  {
    title: "Top 7 databases",
    terms: ["postgres", "redis", "mysql", "mongodb", "elasticsearch", "cassandra", "dynamodb"],
    story: "The data stores in the stacks companies are hiring for.",
  },
  {
    title: "Top 6 infra & devops",
    terms: ["docker", "kubernetes", "terraform", "ansible", "jenkins", "prometheus"],
    story: "The infrastructure and DevOps tools teams hire to run their stacks.",
  },
  {
    title: "Top 5 clouds",
    terms: ["aws", "gcp", "azure", "heroku", "cloudflare"],
    story: "Cloud platform demand - AWS versus the rest.",
  },
  {
    title: "Top 6 functional languages",
    terms: ["scala", "elixir", "clojure", "haskell", "erlang", "ocaml"],
    story: "How much the functional world actually hires, year by year.",
  },
  {
    title: "Top 6 ai & ml skills",
    terms: ["ai", "machine learning", "nlp", "tensorflow", "llm", "pytorch"],
    story: "The machine-learning and generative-AI hiring wave.",
  },
  {
    title: "Top 5 data engineering",
    terms: ["kafka", "spark", "hadoop", "airflow", "snowflake"],
    story: "The data-pipeline stack companies hire to move and crunch data.",
  },
  {
    title: "Top 4 low-level skills",
    terms: ["embedded", "firmware", "assembly", "fpga"],
    story: "Bare-metal, embedded and hardware-adjacent hiring.",
  },
];

/** Popular head-to-head comparisons (2-4 terms, incl. |-OR-group stories) plus
 *  demoted small categories. */
export const COMPARISONS: GalleryCard[] = [
  {
    title: "onsite vs remote vs hybrid",
    terms: ["onsite", "remote", "hybrid"],
    story: "The defining shift in how companies hire: onsite leads a decade, remote erupts in 2021, hybrid emerges after.",
  },
  {
    title: "javascript vs typescript",
    terms: ["javascript", "typescript"],
    story: "The TypeScript takeover, measured in what companies list as wanted skills.",
  },
  {
    title: "react vs vue vs angular",
    terms: ["react", "vue", "angular"],
    story: "Frontend framework demand: React pulls decisively ahead of Vue and Angular.",
  },
  {
    title: "golang vs rust",
    terms: ["golang", "rust"],
    story: "The systems-language race for hires: Go's early lead, Rust's steady climb.",
  },
  {
    title: "tensorflow vs pytorch",
    terms: ["tensorflow", "pytorch"],
    story: "The ML-framework changing of the guard, in hiring.",
  },
  {
    title: "aws vs azure vs gcp",
    terms: ["aws", "azure", "gcp"],
    story: "Cloud demand: AWS the default, Azure and GCP fighting for a distant second.",
  },
  {
    title: "mysql vs mongodb vs postgres",
    terms: ["mysql", "mongodb", "postgres"],
    story: "Database demand, era by era: MySQL, the NoSQL wave, then Postgres on top.",
  },
  {
    title: "docker vs kubernetes",
    terms: ["docker", "kubernetes"],
    story: "The container handoff: Docker as the entry skill, Kubernetes as the must-have.",
  },
  {
    title: "python vs java",
    terms: ["python", "java"],
    story: "Two old workhorses: Java's enterprise base versus Python's relentless climb.",
  },
  {
    title: "ruby vs python",
    terms: ["ruby", "python"],
    story: "Ruby's Rails-era heyday versus Python's steady takeover of the same roles.",
  },
  {
    title: "rails vs django",
    terms: ["rails", "django"],
    story: "The two great web frameworks of the 2010s: Rails out front, Django closing in.",
  },
  {
    title: "scala vs kotlin vs clojure",
    terms: ["scala", "kotlin", "clojure"],
    story: "Three JVM challengers, each with its moment in the hiring threads.",
  },
  {
    title: "docker vs terraform vs ansible",
    terms: ["docker", "terraform", "ansible"],
    story: "Infra-as-code in job posts: Docker first, then Terraform and Ansible.",
  },
  {
    title: "postgres vs mysql",
    terms: ["postgres", "mysql"],
    story: "The relational-database swing: MySQL's early lead, Postgres pulling ahead.",
  },
  {
    title: "aws vs heroku",
    terms: ["aws", "heroku"],
    story: "The PaaS-to-cloud migration, as companies move off Heroku onto AWS.",
  },
  {
    title: "machine learning vs blockchain",
    terms: ["machine learning", "blockchain"],
    story: "Two hype waves in hiring: the ML build-out versus the blockchain spike.",
  },
  {
    title: "ios vs android",
    terms: ["ios", "android"],
    story: "The mobile duopoly in hiring demand, year by year.",
  },
  {
    title: "startup vs enterprise",
    terms: ["startup", "enterprise"],
    story: "How job posts frame themselves: scrappy startup versus established enterprise.",
  },
  {
    title: "backend / infra vs frontend",
    terms: ["backend|sre|devops|infra", "frontend|web design|ui|css"],
    story: "Backend and infra demand versus frontend demand - near-synonyms folded into one bar each with |.",
  },
  {
    title: "AI wave vs crypto wave",
    terms: ["ai|machine learning|llm", "blockchain|crypto|web3"],
    story: "Two hype cycles head to head: the AI/ML bucket versus the blockchain/crypto bucket.",
  },
  {
    title: "systems languages",
    terms: ["golang", "rust"],
    story: "Low-level and systems-programming demand.",
  },
  {
    title: "gpu & shader skills",
    terms: ["metal", "opengl", "cuda"],
    story: "GPU, graphics and shader work in job posts.",
  },
  {
    title: "security",
    terms: ["security", "cryptography", "penetration testing"],
    story: "Security and cryptography roles across the hiring threads.",
  },
];

/** Flat union of every gallery card, in display order. */
export const GALLERY: GalleryCard[] = [...CATEGORY_CARDS, ...COMPARISONS];

/* -------------------------------------------- term enumeration + relations */
/* These power the internal linking on the programmatic SEO routes (T17): a
 * term's siblings come from the category cards it sits in, and the comparisons
 * it appears in come from the head-to-head set. Plain-term only (an OR-group
 * like "ai|ml" is a series, not a single landing term), pure data. */

/** Lowercase comparison: trim + collapse case so "Golang" and "golang" match. */
function norm(s: string): string {
  return s.trim().toLowerCase();
}

/** Every DISTINCT plain term (no `|` OR-groups) that appears anywhere in the
 *  gallery - the candidate set for `/who-is-hiring/[term]` pages. */
export function allGalleryTerms(): string[] {
  const set = new Set<string>();
  for (const card of GALLERY) {
    for (const t of card.terms) {
      if (t.includes("|")) continue; // OR-groups are series, not single terms
      set.add(norm(t));
    }
  }
  return [...set];
}

/** Every DISTINCT series string used in comparisons (incl. `|` OR-groups), so a
 *  `/who-is-hiring/compare/[slug]` page exists for each head-to-head story. */
export function comparisonTermSets(): string[][] {
  return COMPARISONS.map((c) => c.terms);
}

/** Same-category siblings for a term: the other plain terms sharing a category
 *  card with it, de-duplicated and capped. Empty when the term isn't catalogued. */
export function jobsSiblingTerms(term: string, n = 6): string[] {
  const t = norm(term);
  const out: string[] = [];
  const seen = new Set<string>([t]);
  for (const card of CATEGORY_CARDS) {
    const terms = card.terms.map(norm);
    if (!terms.includes(t)) continue;
    for (const other of terms) {
      if (other.includes("|") || seen.has(other)) continue;
      seen.add(other);
      out.push(other);
      if (out.length >= n) return out;
    }
  }
  return out;
}

/** Comparison cards that include this term (as a whole series or inside an
 *  OR-group), for "term head-to-head" cross-links on the term page. */
export function jobsComparisonsForTerm(term: string): GalleryCard[] {
  const t = norm(term);
  return COMPARISONS.filter((c) =>
    c.terms.some((s) => s.split("|").map(norm).includes(t)),
  );
}
