// GENERATED by scripts/ingest-jobs.ts - do not edit by hand.
// The monthly "Ask HN: Who is hiring?" threads, discovered from the Upstash
// `hn` Search index, with each thread's top-level comment count (= the number
// of job postings that month). Re-run the script to refresh after a new month.

export type HiringThread = {
  /** "YYYY-MM" of the thread's post date. */
  month: string;
  /** HN item id of the "Who is hiring?" story. */
  id: number;
  /** Top-level comments under the thread = job postings that month. */
  posts: number;
};

/** The most recent month present in the manifest (data-freshness marker). */
export const JOBS_LATEST_MONTH = "2026-06";

/** Total job postings indexed across all threads. */
export const JOBS_TOTAL_POSTS = 93683;

/** Median job postings per healthy month (>= 30 posts). */
export const JOBS_MEDIAN_POSTS = 480;

export const WHO_IS_HIRING_THREADS: HiringThread[] = [
  {
    "month": "2011-04",
    "id": 2396027,
    "posts": 218
  },
  {
    "month": "2011-05",
    "id": 2503204,
    "posts": 216
  },
  {
    "month": "2011-06",
    "id": 2607052,
    "posts": 256
  },
  {
    "month": "2011-08",
    "id": 2831646,
    "posts": 230
  },
  {
    "month": "2011-09",
    "id": 2949787,
    "posts": 190
  },
  {
    "month": "2011-10",
    "id": 3060221,
    "posts": 196
  },
  {
    "month": "2011-11",
    "id": 3181796,
    "posts": 230
  },
  {
    "month": "2011-12",
    "id": 3300371,
    "posts": 1
  },
  {
    "month": "2012-01",
    "id": 3412900,
    "posts": 149
  },
  {
    "month": "2012-02",
    "id": 3537881,
    "posts": 201
  },
  {
    "month": "2012-03",
    "id": 3652041,
    "posts": 251
  },
  {
    "month": "2012-04",
    "id": 3783657,
    "posts": 201
  },
  {
    "month": "2012-05",
    "id": 3913997,
    "posts": 231
  },
  {
    "month": "2012-06",
    "id": 4053076,
    "posts": 227
  },
  {
    "month": "2012-07",
    "id": 4184755,
    "posts": 194
  },
  {
    "month": "2012-08",
    "id": 4323597,
    "posts": 245
  },
  {
    "month": "2012-09",
    "id": 4463689,
    "posts": 215
  },
  {
    "month": "2012-10",
    "id": 4596375,
    "posts": 248
  },
  {
    "month": "2012-11",
    "id": 4727241,
    "posts": 221
  },
  {
    "month": "2012-12",
    "id": 4857714,
    "posts": 230
  },
  {
    "month": "2013-01",
    "id": 4992617,
    "posts": 192
  },
  {
    "month": "2013-02",
    "id": 5150834,
    "posts": 219
  },
  {
    "month": "2013-03",
    "id": 5304169,
    "posts": 291
  },
  {
    "month": "2013-04",
    "id": 5472746,
    "posts": 343
  },
  {
    "month": "2013-05",
    "id": 5637663,
    "posts": 322
  },
  {
    "month": "2013-06",
    "id": 5803764,
    "posts": 263
  },
  {
    "month": "2013-07",
    "id": 5970187,
    "posts": 291
  },
  {
    "month": "2013-08",
    "id": 6139927,
    "posts": 308
  },
  {
    "month": "2013-09",
    "id": 6310234,
    "posts": 240
  },
  {
    "month": "2013-10",
    "id": 6475879,
    "posts": 426
  },
  {
    "month": "2013-11",
    "id": 6653437,
    "posts": 297
  },
  {
    "month": "2013-12",
    "id": 6827554,
    "posts": 263
  },
  {
    "month": "2014-01",
    "id": 6995020,
    "posts": 222
  },
  {
    "month": "2014-02",
    "id": 7162197,
    "posts": 329
  },
  {
    "month": "2014-03",
    "id": 7324236,
    "posts": 339
  },
  {
    "month": "2014-04",
    "id": 7507765,
    "posts": 356
  },
  {
    "month": "2014-05",
    "id": 7679431,
    "posts": 409
  },
  {
    "month": "2014-06",
    "id": 7829042,
    "posts": 343
  },
  {
    "month": "2014-07",
    "id": 7970366,
    "posts": 420
  },
  {
    "month": "2014-08",
    "id": 8120070,
    "posts": 480
  },
  {
    "month": "2014-09",
    "id": 8252715,
    "posts": 280
  },
  {
    "month": "2014-10",
    "id": 8394339,
    "posts": 354
  },
  {
    "month": "2014-11",
    "id": 8542892,
    "posts": 343
  },
  {
    "month": "2014-12",
    "id": 8681040,
    "posts": 464
  },
  {
    "month": "2015-01",
    "id": 8822808,
    "posts": 275
  },
  {
    "month": "2015-02",
    "id": 8980047,
    "posts": 495
  },
  {
    "month": "2015-03",
    "id": 9127232,
    "posts": 507
  },
  {
    "month": "2015-06",
    "id": 9639001,
    "posts": 587
  },
  {
    "month": "2015-07",
    "id": 9812245,
    "posts": 840
  },
  {
    "month": "2015-08",
    "id": 9996333,
    "posts": 789
  },
  {
    "month": "2015-09",
    "id": 10152809,
    "posts": 703
  },
  {
    "month": "2015-10",
    "id": 10311580,
    "posts": 624
  },
  {
    "month": "2015-11",
    "id": 10492086,
    "posts": 709
  },
  {
    "month": "2015-12",
    "id": 10655740,
    "posts": 359
  },
  {
    "month": "2016-01",
    "id": 10822019,
    "posts": 373
  },
  {
    "month": "2016-02",
    "id": 11012044,
    "posts": 650
  },
  {
    "month": "2016-03",
    "id": 11202954,
    "posts": 671
  },
  {
    "month": "2016-04",
    "id": 11405239,
    "posts": 595
  },
  {
    "month": "2016-05",
    "id": 11611867,
    "posts": 666
  },
  {
    "month": "2016-06",
    "id": 11814828,
    "posts": 774
  },
  {
    "month": "2016-07",
    "id": 12016568,
    "posts": 688
  },
  {
    "month": "2016-08",
    "id": 12202865,
    "posts": 739
  },
  {
    "month": "2016-09",
    "id": 12405698,
    "posts": 646
  },
  {
    "month": "2016-10",
    "id": 12627852,
    "posts": 793
  },
  {
    "month": "2016-11",
    "id": 12846216,
    "posts": 844
  },
  {
    "month": "2016-12",
    "id": 13080280,
    "posts": 642
  },
  {
    "month": "2017-01",
    "id": 13301832,
    "posts": 621
  },
  {
    "month": "2017-02",
    "id": 13541679,
    "posts": 950
  },
  {
    "month": "2017-03",
    "id": 13764728,
    "posts": 792
  },
  {
    "month": "2017-04",
    "id": 14023198,
    "posts": 719
  },
  {
    "month": "2017-05",
    "id": 14238005,
    "posts": 840
  },
  {
    "month": "2017-06",
    "id": 14460777,
    "posts": 734
  },
  {
    "month": "2017-07",
    "id": 14688684,
    "posts": 764
  },
  {
    "month": "2017-08",
    "id": 14901313,
    "posts": 733
  },
  {
    "month": "2017-09",
    "id": 15148885,
    "posts": 783
  },
  {
    "month": "2017-10",
    "id": 15384262,
    "posts": 892
  },
  {
    "month": "2017-11",
    "id": 15601729,
    "posts": 915
  },
  {
    "month": "2017-12",
    "id": 15824597,
    "posts": 784
  },
  {
    "month": "2018-01",
    "id": 16052538,
    "posts": 673
  },
  {
    "month": "2018-02",
    "id": 16282819,
    "posts": 798
  },
  {
    "month": "2018-03",
    "id": 16492994,
    "posts": 872
  },
  {
    "month": "2018-04",
    "id": 16735011,
    "posts": 848
  },
  {
    "month": "2018-05",
    "id": 16967543,
    "posts": 983
  },
  {
    "month": "2018-06",
    "id": 17205865,
    "posts": 771
  },
  {
    "month": "2018-07",
    "id": 17442187,
    "posts": 744
  },
  {
    "month": "2018-08",
    "id": 17663077,
    "posts": 878
  },
  {
    "month": "2018-09",
    "id": 17902901,
    "posts": 700
  },
  {
    "month": "2018-10",
    "id": 18113144,
    "posts": 910
  },
  {
    "month": "2018-11",
    "id": 18354503,
    "posts": 870
  },
  {
    "month": "2018-12",
    "id": 18589702,
    "posts": 766
  },
  {
    "month": "2019-01",
    "id": 18807017,
    "posts": 776
  },
  {
    "month": "2019-02",
    "id": 19055166,
    "posts": 701
  },
  {
    "month": "2019-03",
    "id": 19281834,
    "posts": 756
  },
  {
    "month": "2019-04",
    "id": 19543940,
    "posts": 754
  },
  {
    "month": "2019-05",
    "id": 19797594,
    "posts": 823
  },
  {
    "month": "2019-06",
    "id": 20083795,
    "posts": 667
  },
  {
    "month": "2019-07",
    "id": 20325925,
    "posts": 765
  },
  {
    "month": "2019-08",
    "id": 20584311,
    "posts": 738
  },
  {
    "month": "2019-09",
    "id": 20867123,
    "posts": 614
  },
  {
    "month": "2019-10",
    "id": 21126014,
    "posts": 728
  },
  {
    "month": "2019-11",
    "id": 21419536,
    "posts": 639
  },
  {
    "month": "2019-12",
    "id": 21683554,
    "posts": 592
  },
  {
    "month": "2020-01",
    "id": 21936440,
    "posts": 580
  },
  {
    "month": "2020-02",
    "id": 22225314,
    "posts": 585
  },
  {
    "month": "2020-03",
    "id": 22465476,
    "posts": 654
  },
  {
    "month": "2020-04",
    "id": 22749308,
    "posts": 461
  },
  {
    "month": "2020-05",
    "id": 23042618,
    "posts": 503
  },
  {
    "month": "2020-06",
    "id": 23379196,
    "posts": 515
  },
  {
    "month": "2020-07",
    "id": 23702122,
    "posts": 544
  },
  {
    "month": "2020-08",
    "id": 24038520,
    "posts": 651
  },
  {
    "month": "2020-09",
    "id": 24342498,
    "posts": 604
  },
  {
    "month": "2020-10",
    "id": 24651639,
    "posts": 715
  },
  {
    "month": "2020-11",
    "id": 24969524,
    "posts": 701
  },
  {
    "month": "2020-12",
    "id": 25266288,
    "posts": 697
  },
  {
    "month": "2021-01",
    "id": 25632982,
    "posts": 714
  },
  {
    "month": "2021-02",
    "id": 25989764,
    "posts": 950
  },
  {
    "month": "2021-03",
    "id": 26304051,
    "posts": 913
  },
  {
    "month": "2021-04",
    "id": 26661443,
    "posts": 891
  },
  {
    "month": "2021-05",
    "id": 27025922,
    "posts": 861
  },
  {
    "month": "2021-06",
    "id": 27355392,
    "posts": 987
  },
  {
    "month": "2021-07",
    "id": 27699704,
    "posts": 896
  },
  {
    "month": "2021-08",
    "id": 28037366,
    "posts": 859
  },
  {
    "month": "2021-09",
    "id": 28380661,
    "posts": 925
  },
  {
    "month": "2021-10",
    "id": 28719320,
    "posts": 802
  },
  {
    "month": "2021-11",
    "id": 29067493,
    "posts": 956
  },
  {
    "month": "2021-12",
    "id": 29405056,
    "posts": 759
  },
  {
    "month": "2022-01",
    "id": 29782099,
    "posts": 672
  },
  {
    "month": "2022-02",
    "id": 30164271,
    "posts": 815
  },
  {
    "month": "2022-03",
    "id": 30515750,
    "posts": 802
  },
  {
    "month": "2022-04",
    "id": 30878761,
    "posts": 757
  },
  {
    "month": "2022-05",
    "id": 31235968,
    "posts": 774
  },
  {
    "month": "2022-06",
    "id": 31582796,
    "posts": 739
  },
  {
    "month": "2022-07",
    "id": 31947297,
    "posts": 539
  },
  {
    "month": "2022-08",
    "id": 32306920,
    "posts": 651
  },
  {
    "month": "2022-09",
    "id": 32677265,
    "posts": 514
  },
  {
    "month": "2022-10",
    "id": 33068421,
    "posts": 469
  },
  {
    "month": "2022-11",
    "id": 33422129,
    "posts": 538
  },
  {
    "month": "2022-12",
    "id": 33818037,
    "posts": 493
  },
  {
    "month": "2023-01",
    "id": 34219335,
    "posts": 381
  },
  {
    "month": "2023-02",
    "id": 34612353,
    "posts": 453
  },
  {
    "month": "2023-03",
    "id": 34983767,
    "posts": 423
  },
  {
    "month": "2023-04",
    "id": 35424807,
    "posts": 372
  },
  {
    "month": "2023-05",
    "id": 35773707,
    "posts": 369
  },
  {
    "month": "2023-06",
    "id": 36152014,
    "posts": 339
  },
  {
    "month": "2023-07",
    "id": 36573871,
    "posts": 313
  },
  {
    "month": "2023-08",
    "id": 36956867,
    "posts": 354
  },
  {
    "month": "2023-09",
    "id": 37351667,
    "posts": 304
  },
  {
    "month": "2023-10",
    "id": 37739028,
    "posts": 322
  },
  {
    "month": "2023-11",
    "id": 38099086,
    "posts": 381
  },
  {
    "month": "2023-12",
    "id": 38490811,
    "posts": 333
  },
  {
    "month": "2024-01",
    "id": 38842977,
    "posts": 276
  },
  {
    "month": "2024-02",
    "id": 39217310,
    "posts": 341
  },
  {
    "month": "2024-03",
    "id": 39562986,
    "posts": 300
  },
  {
    "month": "2024-04",
    "id": 39894820,
    "posts": 290
  },
  {
    "month": "2024-05",
    "id": 40224213,
    "posts": 398
  },
  {
    "month": "2024-06",
    "id": 40563283,
    "posts": 341
  },
  {
    "month": "2024-07",
    "id": 40846428,
    "posts": 381
  },
  {
    "month": "2024-08",
    "id": 41129813,
    "posts": 327
  },
  {
    "month": "2024-09",
    "id": 41425910,
    "posts": 303
  },
  {
    "month": "2024-10",
    "id": 41709301,
    "posts": 332
  },
  {
    "month": "2024-11",
    "id": 42017580,
    "posts": 318
  },
  {
    "month": "2024-12",
    "id": 42297424,
    "posts": 332
  },
  {
    "month": "2025-01",
    "id": 42575537,
    "posts": 277
  },
  {
    "month": "2025-02",
    "id": 42919502,
    "posts": 401
  },
  {
    "month": "2025-03",
    "id": 43243024,
    "posts": 358
  },
  {
    "month": "2025-04",
    "id": 43547611,
    "posts": 310
  },
  {
    "month": "2025-05",
    "id": 43858554,
    "posts": 304
  },
  {
    "month": "2025-06",
    "id": 44159528,
    "posts": 365
  },
  {
    "month": "2025-07",
    "id": 44434576,
    "posts": 334
  },
  {
    "month": "2025-08",
    "id": 44757794,
    "posts": 309
  },
  {
    "month": "2025-09",
    "id": 45093192,
    "posts": 305
  },
  {
    "month": "2025-10",
    "id": 45438503,
    "posts": 347
  },
  {
    "month": "2025-11",
    "id": 45800465,
    "posts": 398
  },
  {
    "month": "2025-12",
    "id": 46108941,
    "posts": 384
  },
  {
    "month": "2026-01",
    "id": 46466074,
    "posts": 280
  },
  {
    "month": "2026-02",
    "id": 46857488,
    "posts": 414
  },
  {
    "month": "2026-03",
    "id": 47219668,
    "posts": 338
  },
  {
    "month": "2026-04",
    "id": 47601859,
    "posts": 310
  },
  {
    "month": "2026-05",
    "id": 47975571,
    "posts": 345
  },
  {
    "month": "2026-06",
    "id": 48357725,
    "posts": 329
  }
];

/** Just the thread ids, for building the scope=jobs query filter. */
export const JOB_THREAD_IDS: number[] = WHO_IS_HIRING_THREADS.map((t) => t.id);
